#!/usr/bin/env node

/**
 * Code Generation Pipeline — Data-First, Code-Second
 *
 * Reads JSON substance definitions from `data/substances/`,
 * validates them against `data/schemas/substance.schema.json`,
 * and generates TypeScript modules in `src/lib/substances/`.
 *
 * Also reads `data/categories.json`, validates against
 * `data/schemas/category.schema.json`, and generates `src/lib/categories.ts`.
 *
 * Generated files:
 *   - src/lib/substances/types.ts        → TypeScript interfaces derived from JSON Schema
 *   - src/lib/substances/substances.ts   → All substance const exports
 *   - src/lib/substances/index.ts        → Main entry: arrays, lookup maps, search
 *   - src/lib/categories.ts              → Category definitions + color mappings
 *   - src/lib/types.ts                   → Re-export bridge
 *
 * Usage:
 *   node scripts/generate.mjs                # validate + generate
 *   node scripts/generate.mjs --validate-only
 *   node scripts/generate.mjs --no-validate
 *   node scripts/generate.mjs --watch        # watch for changes and regenerate
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, watchFile, unwatchFile } from 'fs';
import { join, basename, relative } from 'path';

// ─── Configuration ──────────────────────────────────────────────────────────

const ROOT = join(import.meta.dirname, '..');
const DATA_DIR = join(ROOT, 'data', 'substances');
const CATEGORIES_PATH = join(ROOT, 'data', 'categories.json');
const SCHEMA_PATH = join(ROOT, 'data', 'schemas', 'substance.schema.json');
const CATEGORY_SCHEMA_PATH = join(ROOT, 'data', 'schemas', 'category.schema.json');
const OUTPUT_DIR = join(ROOT, 'src', 'lib', 'substances');
const AUTOGEN_HEADER = '// Auto-generated by scripts/generate.mjs — do not edit manually.\n';

const args = process.argv.slice(2);
const validateOnly = args.includes('--validate-only');
const skipValidate = args.includes('--no-validate');
const watchMode = args.includes('--watch');

// ─── Utility: Convert substance id to valid JS variable name ─────────────────

function idToVarName(id) {
  let name = id.replace(/-/g, '_');
  if (/^[0-9]/.test(name)) {
    name = '_' + name;
  }
  return name;
}

// ─── JSON Schema → TypeScript type derivation ───────────────────────────────

/**
 * Derives TypeScript type definitions from a JSON Schema object.
 * Handles: string enums, arrays, objects, $ref, additionalProperties,
 * optional properties, and nested definitions.
 */
function schemaToTsTypes(schema) {
  const defs = schema.$defs || schema.definitions || {};
  const lines = [];

  // Process each definition
  for (const [defName, defSchema] of Object.entries(defs)) {
    lines.push(generateTypeDef(defName, defSchema, defs));
  }

  // Process the root type
  const rootName = schema.title || 'Root';
  lines.push(generateTypeDef(rootName, schema, defs, true));

  return lines.join('\n\n');
}

function generateTypeDef(name, schema, defs, isRoot = false) {
  // Enum type
  if (schema.enum) {
    const union = schema.enum.map(v => `'${v}'`).join(' |\n  ');
    return `export type ${name} =\n  ${union};`;
  }

  // Object type (interface)
  if (schema.type === 'object') {
    const required = new Set(schema.required || []);
    const props = Object.entries(schema.properties || {});

    if (props.length === 0 && schema.additionalProperties) {
      // Dictionary/map type
      const valueSchema = schema.additionalProperties === true
        ? { type: 'unknown' }
        : schema.additionalProperties;

      if (valueSchema.$ref) {
        const refName = valueSchema.$ref.replace('#/$defs/', '').replace('#/definitions/', '');
        return `export type ${name} = Partial<Record<string, ${refName}>>;`;
      }
      const valueType = resolveTypeRef(valueSchema, defs);
      return `export type ${name} = Record<string, ${valueType}>;`;
    }

    const propLines = props.map(([propName, propSchema]) => {
      const isOptional = !required.has(propName);
      const tsType = resolveTypeRef(propSchema, defs);
      const optional = isOptional ? '?' : '';
      return `  ${propName}${optional}: ${tsType};`;
    });

    return `export interface ${name} {\n${propLines.join('\n')}\n}`;
  }

  // Array type
  if (schema.type === 'array') {
    const itemType = resolveTypeRef(schema.items || { type: 'unknown' }, defs);
    return `export type ${name} = ${itemType}[];`;
  }

  return `export type ${name} = unknown;`;
}

function resolveTypeRef(schema, defs) {
  // Resolve $ref
  if (schema.$ref) {
    const refName = schema.$ref.replace('#/$defs/', '').replace('#/definitions/', '');
    // Capitalize first letter for TypeScript convention
    return refName.charAt(0).toUpperCase() + refName.slice(1);
  }

  // String type
  if (schema.type === 'string') {
    if (schema.enum) {
      return schema.enum.map(v => `'${v}'`).join(' | ');
    }
    return 'string';
  }

  // Number type
  if (schema.type === 'number' || schema.type === 'integer') {
    return 'number';
  }

  // Boolean type
  if (schema.type === 'boolean') {
    return 'boolean';
  }

  // Array type
  if (schema.type === 'array') {
    const itemType = resolveTypeRef(schema.items || { type: 'unknown' }, defs);
    return `${itemType}[]`;
  }

  // Object type (inline)
  if (schema.type === 'object') {
    if (schema.additionalProperties) {
      const valueSchema = schema.additionalProperties === true
        ? { type: 'unknown' }
        : schema.additionalProperties;
      const valueType = resolveTypeRef(valueSchema, defs);
      return `Record<string, ${valueType}>`;
    }
    return 'Record<string, unknown>';
  }

  return 'unknown';
}

/**
 * Generate TypeScript types from the JSON Schema.
 * Uses schema-derived types with manual refinements for complex cases.
 */
function generateTypesTs(schema) {
  const defs = schema.$defs || {};

  // Build enum types from schema definitions
  const categoryEnum = (defs.substanceCategory?.enum || []).map(v => `'${v}'`).join(' |\n  ');
  const riskLevelEnum = (defs.riskLevel?.enum || []).map(v => `'${v}'`).join(' |\n  ');
  const defaultUnitEnum = (defs.defaultUnit?.enum || []).map(v => `'${v}'`).join(' |\n  ');
  const routeEnum = (defs.route?.enum || []).map(v => `'${v}'`).join(' |\n  ');

  // Build interfaces from schema
  const dosageRequired = defs.dosageLevels?.required || [];
  const dosageProps = Object.entries(defs.dosageLevels?.properties || {});
  const durationRequired = defs.durationPhases?.required || [];
  const durationProps = Object.entries(defs.durationPhases?.properties || {});

  return `${AUTOGEN_HEADER}
// Source: data/schemas/substance.schema.json
// Regenerate with: npm run generate
//
// ⚠️  DO NOT EDIT — changes will be overwritten on next generation.
//     To modify types, update the JSON Schema at data/schemas/substance.schema.json
//     then run: npm run generate

${categoryEnum ? `export type SubstanceCategory =\n  ${categoryEnum};` : ''}

${riskLevelEnum ? `export type RiskLevel =\n  ${riskLevelEnum};` : ''}

${defaultUnitEnum ? `export type DefaultUnit =\n  ${defaultUnitEnum};` : ''}

${routeEnum ? `export type Route =\n  ${routeEnum};` : ''}

export interface DosageLevels {
${dosageProps.map(([name, sch]) => `  ${name}${dosageRequired.includes(name) ? '' : '?'}: string;`).join('\n')}
}

export interface DurationPhases {
${durationProps.map(([name, sch]) => `  ${name}${durationRequired.includes(name) ? '' : '?'}: string;`).join('\n')}
}

export interface RouteDosageDuration {
  dosage: DosageLevels;
  duration: DurationPhases;
${defs.routeDosageDuration?.properties?.notes ? '  notes?: string;\n' : ''}}

export interface Interactions {
${Object.entries(defs.interactions?.properties || {}).map(([name, sch]) => `  ${name}: string[];`).join('\n')}
}

export interface Effects {
${Object.entries(defs.effects?.properties || {}).map(([name, sch]) => `  ${name}: string[];`).join('\n')}
}

export interface Chemistry {
${Object.entries(defs.chemistry?.properties || {}).map(([name, sch]) => `  ${name}: string;`).join('\n')}
}

export interface CategoryInfo {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  substances: string[];
}

export interface Substance {
${Object.entries(schema.properties || {}).map(([name, sch]) => {
  const required = (schema.required || []).includes(name);
  const optional = required ? '' : '?';

  if (sch.$ref) {
    const refName = sch.$ref.replace('#/$defs/', '');
    const typeName = refName.charAt(0).toUpperCase() + refName.slice(1);
    return `  ${name}${optional}: ${typeName};`;
  }
  if (sch.type === 'string') return `  ${name}${optional}: string;`;
  if (sch.type === 'array') {
    const items = sch.items;
    if (items?.$ref) {
      const refName = items.$ref.replace('#/$defs/', '');
      const typeName = refName.charAt(0).toUpperCase() + refName.slice(1);
      return `  ${name}${optional}: ${typeName}[];`;
    }
    return `  ${name}${optional}: string[];`;
  }
  if (sch.type === 'object') {
    if (sch.additionalProperties?.$ref) {
      const refName = sch.additionalProperties.$ref.replace('#/$defs/', '');
      const typeName = refName.charAt(0).toUpperCase() + refName.slice(1);
      return `  ${name}${optional}: Partial<Record<Route, ${typeName}>>;`;
    }
    if (sch.additionalProperties) return `  ${name}${optional}: Record<string, unknown>;`;
    return `  ${name}${optional}: Record<string, unknown>;`;
  }
  return `  ${name}${optional}: unknown;`;
}).join('\n')}
}

// ─── TripSit Combo Types (sourced from TripSit/drugs combos.json) ──────────

export interface TripSitComboSource {
  author: string;
  title: string;
  url: string;
}

export interface TripSitCombo {
  drugA: string;
  drugB: string;
  status: string;
  note: string;
  sources: TripSitComboSource[];
}
`;
}

// ─── Validation with Ajv ─────────────────────────────────────────────────────

/**
 * Validate a single data object (non-array) against a JSON Schema.
 */
async function validateSingle(data, schema, label) {
  let Ajv, addFormats;
  try {
    const AjvModule = await import('ajv');
    Ajv = AjvModule.default || AjvModule;
  } catch {
    const { execSync } = await import('child_process');
    execSync('npm install --save-dev ajv@8 ajv-formats', { cwd: ROOT, stdio: 'inherit' });
    const AjvModule = await import('ajv');
    Ajv = AjvModule.default || AjvModule;
  }

  const ajv = new Ajv({ allErrors: true, strict: false });
  try {
    const formatsModule = await import('ajv-formats');
    addFormats = formatsModule.default || formatsModule;
    addFormats(ajv);
  } catch { /* optional */ }

  const schemaForValidate = { ...schema };
  delete schemaForValidate.$schema;
  const validate = ajv.compile(schemaForValidate);

  const errors = [];
  if (!validate(data)) {
    const msgs = (validate.errors || [])
      .map(e => `  ${e.instancePath || '/'} ${e.message}`)
      .join('; ');
    errors.push(`❌ ${label}: ${msgs}`);
  }
  return errors;
}

async function validateWithSchema(data, schema, label) {
  let Ajv, addFormats;
  try {
    const AjvModule = await import('ajv');
    Ajv = AjvModule.default || AjvModule;
  } catch {
    console.log('   ⚠️  ajv not installed — installing...');
    const { execSync } = await import('child_process');
    execSync('npm install --save-dev ajv@8 ajv-formats', { cwd: ROOT, stdio: 'inherit' });
    const AjvModule = await import('ajv');
    Ajv = AjvModule.default || AjvModule;
  }

  const ajv = new Ajv({ allErrors: true, strict: false });

  try {
    const formatsModule = await import('ajv-formats');
    addFormats = formatsModule.default || formatsModule;
    addFormats(ajv);
  } catch {
    // formats optional
  }

  const schemaForValidate = { ...schema };
  delete schemaForValidate.$schema;

  const validate = ajv.compile(schemaForValidate);
  const errors = [];

  if (Array.isArray(data)) {
    for (const item of data) {
      if (!validate(item)) {
        const msgs = (validate.errors || [])
          .map(e => `  ${e.instancePath || '/'} ${e.message}`)
          .join('; ');
        errors.push(`❌ ${item.id || label}: ${msgs}`);
      }
    }
  } else {
    if (!validate(data)) {
      const msgs = (validate.errors || [])
        .map(e => `  ${e.instancePath || '/'} ${e.message}`)
        .join('; ');
      errors.push(`❌ ${label}: ${msgs}`);
    }
  }

  return errors;
}

// ─── Main Pipeline ──────────────────────────────────────────────────────────

async function run() {
  const startTime = Date.now();

  // ─── Step 1: Load JSON Schema ────────────────────────────────────────────

  console.log('📋 Loading JSON Schema...');
  const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

  // ─── Step 2: Load all substance JSON files ──────────────────────────────

  console.log('📂 Loading substance data from data/substances/...');
  const jsonFiles = readdirSync(DATA_DIR)
    .filter(f => f.endsWith('.json'))
    .sort();

  console.log(`   Found ${jsonFiles.length} substance files`);

  const substances = [];
  const parseErrors = [];

  for (const file of jsonFiles) {
    try {
      const raw = readFileSync(join(DATA_DIR, file), 'utf-8');
      const data = JSON.parse(raw);
      substances.push(data);
    } catch (err) {
      parseErrors.push(`❌ ${file}: ${err.message}`);
    }
  }

  if (parseErrors.length > 0) {
    console.error('\n⚠️  Parse errors:');
    parseErrors.forEach(e => console.error(`   ${e}`));
    process.exit(1);
  }

  // ─── Step 3: Validate against JSON Schema ──────────────────────────────

  if (!skipValidate) {
    console.log('✅ Validating substances against JSON Schema...');
    const validationErrors = await validateWithSchema(substances, schema, 'substance');

    if (validationErrors.length > 0) {
      console.error(`\n⚠️  Validation failed for ${validationErrors.length} substances:`);
      validationErrors.slice(0, 20).forEach(e => console.error(`   ${e}`));
      if (validationErrors.length > 20) {
        console.error(`   ... and ${validationErrors.length - 20} more`);
      }
      process.exit(1);
    }

    console.log(`   ✅ All ${substances.length} substances pass schema validation`);

    // Validate categories if schema and data exist
    if (existsSync(CATEGORIES_PATH)) {
      const categoriesData = JSON.parse(readFileSync(CATEGORIES_PATH, 'utf-8'));
      if (existsSync(CATEGORY_SCHEMA_PATH)) {
        const catSchema = JSON.parse(readFileSync(CATEGORY_SCHEMA_PATH, 'utf-8'));
        console.log('✅ Validating categories against JSON Schema...');
        const catErrors = await validateSingle(categoriesData, catSchema, 'categories');
        if (catErrors.length > 0) {
          console.error(`\n⚠️  Category validation failed:`);
          catErrors.forEach(e => console.error(`   ${e}`));
          process.exit(1);
        }
        console.log(`   ✅ All ${categoriesData.length} categories pass schema validation`);
      }
    }
  } else {
    console.log('   ⏭️  Skipping validation (--no-validate)');
  }

  if (validateOnly) {
    const elapsed = Date.now() - startTime;
    console.log(`\n✅ Validation complete in ${elapsed}ms. Exiting (--validate-only).`);
    process.exit(0);
  }

  // ─── Step 4: Generate TypeScript types (schema-derived) ────────────────

  console.log('🔧 Generating TypeScript types (derived from JSON Schema)...');

  const typesContent = generateTypesTs(schema);

  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(join(OUTPUT_DIR, 'types.ts'), typesContent);
  console.log('   ✅ types.ts');

  // ─── Step 5: Generate substances data module ──────────────────────────

  console.log('🔧 Generating substances data module...');

  const sortedSubstances = [...substances].sort((a, b) => a.id.localeCompare(b.id));

  const varExports = sortedSubstances.map(sub => {
    const varName = idToVarName(sub.id);
    const jsonStr = JSON.stringify(sub, null, 2);
    return `export const ${varName}: Substance = ${jsonStr} as const;`;
  }).join('\n\n');

  const substancesContent = `${AUTOGEN_HEADER}
import type { Substance } from './types';

${varExports}
`;

  writeFileSync(join(OUTPUT_DIR, 'substances.ts'), substancesContent);
  console.log(`   ✅ substances.ts (${sortedSubstances.length} substances)`);

  // ─── Step 6: Generate index.ts with lookup maps and search ──────────────

  console.log('🔧 Generating index.ts with lookup maps...');

  // Build category mapping from data
  const categoryMap = {};
  for (const sub of sortedSubstances) {
    for (const cat of sub.categories) {
      if (!categoryMap[cat]) categoryMap[cat] = [];
      categoryMap[cat].push(sub.id);
    }
  }

  const importNames = sortedSubstances.map(sub => idToVarName(sub.id));

  const indexContent = `${AUTOGEN_HEADER}

// Re-export types
export type {
  Substance,
  SubstanceCategory,
  RiskLevel,
  DefaultUnit,
  Route,
  RouteDosageDuration,
  DosageLevels,
  DurationPhases,
  Interactions,
  Effects,
  Chemistry,
  CategoryInfo,
  TripSitCombo,
  TripSitComboSource,
} from './types';

// Re-export individual substances
export {
${importNames.map(n => `  ${n},`).join('\n')}
} from './substances';

import { Substance, SubstanceCategory } from './types';
import {
${importNames.map(n => `  ${n},`).join('\n')}
} from './substances';

// ─── Substance Array ────────────────────────────────────────────────────────

export const substances: Substance[] = [
${importNames.map(n => `  ${n},`).join('\n')}
];

// ─── Lookup Maps ────────────────────────────────────────────────────────────

const substancesById: Record<string, Substance> = {
${sortedSubstances.map(sub => `  '${sub.id}': ${idToVarName(sub.id)},`).join('\n')}
};

const substancesByCategory: Record<string, Substance[]> = {
${Object.entries(categoryMap).sort(([a], [b]) => a.localeCompare(b)).map(([cat, ids]) => {
  const varRefs = ids.map(id => idToVarName(id)).join(',\n    ');
  return `  '${cat}': [\n    ${varRefs}\n  ],`;
}).join('\n')}
};

// ─── Query Functions ────────────────────────────────────────────────────────

/**
 * Get a substance by its unique ID
 */
export function getSubstanceById(id: string): Substance | undefined {
  return substancesById[id];
}

/**
 * Get all substances in a specific category
 */
export function getSubstancesByCategory(category: string): Substance[] {
  return substancesByCategory[category] ? [...substancesByCategory[category]] : [];
}

/**
 * Search substances by name, common names, aliases, or description
 */
export function searchSubstances(query: string): Substance[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  return substances.filter(s =>
    s.name.toLowerCase().includes(lowerQuery) ||
    (s.commonNames || []).some((n: string) => n.toLowerCase().includes(lowerQuery)) ||
    (s.aliases || []).some((a: string) => a.toLowerCase().includes(lowerQuery)) ||
    s.description.toLowerCase().includes(lowerQuery)
  );
}

/**
 * Search substances with relevance ranking and fuzzy matching.
 * Returns results sorted by relevance score (highest first).
 */
export function searchSubstancesRanked(
  query: string,
  options?: {
    categoryFilter?: string | null;
    limit?: number;
  }
): { substance: Substance; score: number; matchField: string }[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  const { categoryFilter, limit = 50 } = options || {};
  const scored: { substance: Substance; score: number; matchField: string }[] = [];

  const wordBoundaryRe = new RegExp(\`(?:^|\\\\s)\${escapeSearchRegex(lowerQuery)}\`, 'i');

  for (const s of substances) {
    if (categoryFilter && !(s.categories || []).includes(categoryFilter as any)) {
      continue;
    }

    let bestScore = 0;
    let bestField = '';

    if (s.name.toLowerCase() === lowerQuery) { bestScore = 1000; bestField = 'name'; }
    else if (s.name.toLowerCase().startsWith(lowerQuery)) { bestScore = 800; bestField = 'name'; }

    if (bestScore < 700) {
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        const nLower = n.toLowerCase();
        if (nLower === lowerQuery && bestScore < 700) { bestScore = 700; bestField = n.length <= 15 ? n : 'name'; break; }
        if (nLower.startsWith(lowerQuery) && bestScore < 600) { bestScore = 600; bestField = n.length <= 15 ? n : 'name'; }
      }
    }

    if (bestScore < 400 && wordBoundaryRe.test(s.name)) { bestScore = 400; bestField = 'name'; }

    if (bestScore < 300) {
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        if (wordBoundaryRe.test(n) && bestScore < 300) { bestScore = 300; bestField = n.length <= 15 ? n : 'name'; break; }
      }
    }

    if (bestScore < 200 && s.name.toLowerCase().includes(lowerQuery)) { bestScore = 200; bestField = 'name'; }

    if (bestScore < 150) {
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        if (n.toLowerCase().includes(lowerQuery) && bestScore < 150) { bestScore = 150; bestField = n.length <= 15 ? n : 'name'; break; }
      }
    }

    if (bestScore < 100 && s.class && s.class.toLowerCase().includes(lowerQuery)) { bestScore = 100; bestField = 'class'; }

    if (bestScore < 80 && (s.categories || []).some((c: string) => c.toLowerCase().includes(lowerQuery))) { bestScore = 80; bestField = 'category'; }

    if (bestScore < 50 && s.description && s.description.toLowerCase().includes(lowerQuery)) { bestScore = 50; bestField = 'description'; }

    if (bestScore < 1 && lowerQuery.length >= 3) {
      const nameLower = s.name.toLowerCase();
      const nameDist = levenshtein(lowerQuery, nameLower);
      if (nameDist <= Math.max(1, Math.floor(lowerQuery.length / 3))) {
        const fuzzyScore = -10 + (lowerQuery.length - nameDist) * 2;
        if (fuzzyScore > bestScore) { bestScore = fuzzyScore; bestField = 'name'; }
      }
      const allNames = [...(s.commonNames || []), ...(s.aliases || [])];
      for (const n of allNames) {
        const nLower = n.toLowerCase();
        if (nLower.length >= lowerQuery.length) {
          const prefix = nLower.substring(0, lowerQuery.length);
          const prefixDist = levenshtein(lowerQuery, prefix);
          if (prefixDist <= Math.max(1, Math.floor(lowerQuery.length / 3))) {
            const fuzzyScore = -10 + (lowerQuery.length - prefixDist);
            if (fuzzyScore > bestScore) { bestScore = fuzzyScore; bestField = n.length <= 15 ? n : 'name'; }
          }
        }
      }
    }

    if (bestScore > 0) {
      scored.push({ substance: s, score: bestScore, matchField: bestField });
    }
  }

  scored.sort((a, b) => b.score - a.score);
  return limit > 0 ? scored.slice(0, limit) : scored;
}

/** Simple Levenshtein distance for fuzzy matching */
function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  let prev = Array.from({ length: n + 1 }, (_, i) => i);
  for (let i = 1; i <= m; i++) {
    const curr = new Array(n + 1);
    curr[0] = i;
    for (let j = 1; j <= n; j++) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      curr[j] = Math.min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost);
    }
    prev = curr;
  }
  return prev[n];
}

function escapeSearchRegex(s: string): string {
  return s.replace(/[.*+?^\${}()|[\\]\\\\]/g, '\\\\$&');
}

// ─── Utility Exports ────────────────────────────────────────────────────────

export function getAllSubstanceIds(): string[] {
  return substances.map(s => s.id);
}

export function getAllSubstanceNames(): string[] {
  return substances.map(s => s.name);
}

export function getSubstancesByRiskLevel(riskLevel: 'low' | 'moderate' | 'high' | 'very-high'): Substance[] {
  return substances.filter(s => s.riskLevel === riskLevel);
}

export function getSubstancesByRoute(route: string): Substance[] {
  return substances.filter(s => s.routes && s.routes.includes(route as any));
}

export function getSubstancesByInteraction(interaction: string): Substance[] {
  const lowerInteraction = interaction.toLowerCase();
  return substances.filter(s => {
    const all = [
      ...(s.interactions.dangerous || []),
      ...(s.interactions.unsafe || []),
      ...(s.interactions.uncertain || []),
      ...(s.interactions.crossTolerances || []),
    ];
    return all.some(i => i.toLowerCase().includes(lowerInteraction));
  });
}

export function getSubstanceCount(): number {
  return substances.length;
}

export function getSubstanceCountByCategory(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const category of Object.keys(substancesByCategory)) {
    counts[category] = substancesByCategory[category].length;
  }
  return counts;
}

// ─── Constants ──────────────────────────────────────────────────────────────

export const CATEGORY_IDS = {
${Object.keys(categoryMap).sort().map(cat => `  ${cat.toUpperCase().replace(/-/g, '_')}: '${cat}' as SubstanceCategory,`).join('\n')}
};

export const RISK_LEVELS = {
  LOW: 'low' as const,
  MODERATE: 'moderate' as const,
  HIGH: 'high' as const,
  VERY_HIGH: 'very-high' as const,
};
`;

  writeFileSync(join(OUTPUT_DIR, 'index.ts'), indexContent);
  console.log(`   ✅ index.ts (with lookup maps & search functions)`);

  // ─── Step 7: Generate categories.ts from data/categories.json ────────────

  if (existsSync(CATEGORIES_PATH)) {
    console.log('🔧 Generating categories.ts from data/categories.json...');
    const categoriesData = JSON.parse(readFileSync(CATEGORIES_PATH, 'utf-8'));

    const categoryDefs = categoriesData.map(cat => `  {
    id: '${cat.id}',
    name: '${cat.name}',
    description: '${cat.description.replace(/'/g, "\\'")}',
    icon: '${cat.icon}',
    color: '${cat.color}'
  }`).join(',\n');

    const categoryColorEntries = categoriesData.map(cat =>
      `  ${cat.id}: '${cat.colorClasses || `text-${cat.color}-500 bg-${cat.color}-500/10 border-${cat.color}-500/20`}',`
    ).join('\n');

    const categoriesTsContent = `${AUTOGEN_HEADER}
// Source: data/categories.json
// Regenerate with: npm run generate
//
// ⚠️  DO NOT EDIT — changes will be overwritten on next generation.
//     To modify categories, update data/categories.json then run: npm run generate

import type { CategoryInfo, SubstanceCategory } from './substances/types';

export const categories: CategoryInfo[] = [
${categoryDefs}
];

export const categoryColors: Record<SubstanceCategory, string> = {
${categoryColorEntries}
};
`;

    writeFileSync(join(ROOT, 'src', 'lib', 'categories.ts'), categoriesTsContent);
    console.log('   ✅ categories.ts');
  }

  // ─── Step 8: Update the legacy types.ts re-export bridge ─────────────────

  const legacyTypesContent = `${AUTOGEN_HEADER}
// This file re-exports from the generated substances module.
// Prefer importing from '@/lib/substances/index' directly.

export type {
  Substance,
  SubstanceCategory,
  RiskLevel,
  RouteDosageDuration,
  Interactions,
  CategoryInfo,
  TripSitCombo,
  TripSitComboSource,
} from './substances/types';
`;

  writeFileSync(join(ROOT, 'src', 'lib', 'types.ts'), legacyTypesContent);
  console.log('   ✅ src/lib/types.ts (re-export bridge)');

  // ─── Summary ────────────────────────────────────────────────────────────

  const elapsed = Date.now() - startTime;
  console.log(`\n🎉 Generation complete in ${elapsed}ms!`);
  console.log(`   ${sortedSubstances.length} substances processed`);
  console.log(`   Files generated:`);
  console.log(`     src/lib/substances/types.ts`);
  console.log(`     src/lib/substances/substances.ts`);
  console.log(`     src/lib/substances/index.ts`);
  console.log(`     src/lib/categories.ts`);
  console.log(`     src/lib/types.ts`);
}

// ─── Watch Mode ──────────────────────────────────────────────────────────────

if (watchMode) {
  console.log('👁️  Watch mode enabled — monitoring data/ for changes...');
  console.log('   Press Ctrl+C to stop.\n');

  // Initial run
  await run();

  // Watch data directories
  const watchedDirs = [DATA_DIR, join(ROOT, 'data', 'schemas')];
  const watchedFiles = [CATEGORIES_PATH];

  let debounceTimer = null;
  const debouncedRun = () => {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(async () => {
      console.log('\n🔄 Change detected — regenerating...');
      try {
        await run();
      } catch (err) {
        console.error('❌ Regeneration failed:', err.message);
      }
    }, 300);
  };

  for (const dir of watchedDirs) {
    try {
      const files = readdirSync(dir);
      for (const file of files) {
        watchFile(join(dir, file), { interval: 1000 }, (curr, prev) => {
          if (curr.mtimeMs !== prev.mtimeMs) {
            console.log(`   📝 ${relative(ROOT, join(dir, file))} changed`);
            debouncedRun();
          }
        });
      }
    } catch {
      // directory may not exist
    }
  }

  for (const file of watchedFiles) {
    if (existsSync(file)) {
      watchFile(file, { interval: 1000 }, (curr, prev) => {
        if (curr.mtimeMs !== prev.mtimeMs) {
          console.log(`   📝 ${relative(ROOT, file)} changed`);
          debouncedRun();
        }
      });
    }
  }

  // Keep process alive
  process.on('SIGINT', () => {
    console.log('\n🛑 Watch mode stopped.');
    process.exit(0);
  });
} else {
  // Single run
  await run();
}
